### ISSUE TITLE
wcs 1.0.0 compliance test getcoverage issue

### ISSUE THREAD

**Issue by greatzzk** [opengeospatial/ets-wcs10#48] opened 2019-10-24 22:41 UTC
test:
Test wcs1-0-0:getcoverage_operations-getcoverage_request-grid_size-post-xml-2

failure info against my wcs server:
A sequence of more than one item is not allowed as the first argument of concat()

possible reason:
what our server returns:
headers:
![image](https://user-images.githubusercontent.com/11200872/67530399-d6fbaa00-f673-11e9-8d3b-0d5ee7f294ef.png)
body:
![image](https://user-images.githubusercontent.com/11200872/67530588-6a34df80-f674-11e9-92d8-5e446216c736.png)
your code:
![image](https://user-images.githubusercontent.com/11200872/67530376-c3e8da00-f673-11e9-9dc0-42a1bfb8d454.png)
there are two header keys contains "Content-Type"

**Comment by keshav-nangare** [comment] 2019-11-12 08:39
@greatzzk 

Can you please provide the service to reproduce this issue?

Thank you!

**Comment by greatzzk** [comment] 2019-11-12 08:42
> @greatzzk
> 
> Can you please provide the service to reproduce this issue?
> 
> Thank you!

check if you can reproduce with service on this server, e.g.:
https://sampleserver6.arcgisonline.com/arcgis/services/ScientificData/SeaTemperature/ImageServer/WCSServer?request=GetCapabilities&service=WCS

if not, i can send the one i used to test tomorrow.

**Comment by keshav-nangare** [comment] 2019-11-12 10:29
@greatzzk 

[1] http://cite.opengeospatial.org/te2

I am able to reproduce this behavior on beta[1] site but not on the local environment.

**Comment by keshav-nangare** [comment] 2019-11-12 10:35
The test suite ets-wcs10 version of the beta site is 1.15, and there are few PR's are merged into master so that the master branch contains fix. The new release of this ets will fix this issue.

This issue is duplicate of #40.

**Closed** 2019-11-13 09:27 UTC
